### PR TITLE
feature: cmyk plugin implementation

### PR DESCRIPTION
**Pull request by EricRovell**
Implemented the CMYK plugin. It adds the functionality to convert the color to CMYK color model object, convert to CMYK color string and parsing the CMYK color objects.
Updated the documentation .
Implemented and ran the tests.

### CODE REVIEW

**Comment by omgovich** [comment]
Oh, wow! Amazing job! 🔥 Thanks s lof for that.

The code looks great but there is a few eslint warning that we need to fix before merge. Run `npm run lint` in the project root to lint the code.

**Comment by EricRovell** [comment]
Got it!

**Review by omgovich — APPROVED** [review]
Great! Thanks again! ❤️

**Comment by EricRovell** [comment]
You are welcome, I will be back with more :)

**Pull request merged**
